### ISSUE TITLE
Add PyTest

### ISSUE THREAD

**Issue by sarcoma** [sarcoma/Invoicing#5]
The project is in dire need for some unit tests. If someone could add PyTest to the project and create a tests folder that'd be great.

**Comment by marcosstefani** [comment]
Hello @sarcoma, I would like to work on this Issue.

**Comment by sarcoma** [comment]
Hey @marcosstefani it's all yours.

**Comment by marcosstefani** [comment]
Okay, any problem I report here.

**Comment by marcosstefani** [comment]
I did not understand how you use the routes. I just understood the main.py that makes interactions via console, and I would rather not implement tests for this because the console is waiting for a return. Thanks, but I'm going to look for projects that I master more like for example using Flask-rest etc.

Thank you.

**Comment by sarcoma** [comment]
@marcosstefani fair enough, the routes where an addition that runs separately from the main app. The main application runs via the commandline the router uses flask. They aren't used together, I used the routes to see how I could create an API from the exisitng codebase.

The Crud and API have a lot of crossover functionality that can be combined when the presentation layer is seperated from the Crud. 

Anyway no problem thanks for taking a look.
